[package]
name        = "rust-boilerplate"
version     = "0.0.0"
description = "🔋 A template for rust projects"
authors     = ["Casey Rodarmor <casey@rodarmor.com>"]
license     = "WTFPL OR MIT OR Apache-2.0"
homepage    = "https://github.com/casey/rust-boilerplate"

[dependencies]
